version: "2"

services:
  appd-ec:
    container_name: appd-ec
    build:
      context: "ec"
    ports:
      - "9191:9191"
      - "8090:8090"
      - "9080:9080"
    networks:
      - app-net
#    volumes:
#      - "./logs/ec:/home/appdynamics/platform/platform-admin/logs"
    entrypoint: /home/appdynamics/entrypoint.ec-controller-event-samehost.sh

  appd-eum:
    container_name: "appd-eum"
    build:
      context: "eum"
    networks:
      - app-net
    ports: 
      - "7001:7001"
      - "7002:7002"
    privileged: true

networks:
  app-net:
    driver: bridge

volumes:
  logs:
